### PR TITLE
fix types

### PR DESCRIPTION
**Pull request by KillWolfVlad**
`joi` has been renamed to `@hapi/joi`, but types don't support it.

### CODE REVIEW

**Comment by arb** [comment]
Can you do this again with the following steps?

```
1. Start clean `rm -rf node_modules`
2. Just install the package lock ... `npm ci`
3. Just Update the package you need `npm update PACKAGE_NAME`
```

I don't want the entire package.lock file regenerated for a single dev dependency if we can help it.

**Comment by KillWolfVlad** [comment]
@arb can you do it on your side? `npm` regenerate `package-lock.json` when I use `install` and `remove` commands.

**Comment by KillWolfVlad** [comment]
@arb do you interested in fixing this issue?

**Comment by arb** [comment]
Yes, I just haven't quite gotten to it yet. Also since it's not preventing anyone from using this library it's not high priority. When I tried it locally, I had almost as many package.lock changes myself so I'm thinking about how I want to handle this.

**Comment by vabhishek-me** [comment]
This is causing issue when you use `@hapi/joi` package. As you are including `joi` internally and providing it, please make sure the types match. This is giving issue in my typescript project. I think merging this pull request will solve it.

**Comment by arb** [comment]
Trumped by #114. Published as 10.0.1.

**Pull request closed without merging**
