### PR TITLE
Update schema.js

### PR DESCRIPTION
**Pull request by 7006**
use Array.prototype.filter to collect an array of error status  codes

### CODE REVIEW

**Comment by arb** [comment]
Thanks for the PR! However, this change two loops to happen where as the way it is currently, does everything in a single pass.

**Comment by 7006** [comment]
@arb how do you feel if we use this package https://github.com/jshttp/statuses to get an array of status codes in the form of numbers ?

**Comment by 7006** [comment]
I have updated pull request

**Comment by arb** [comment]
I'm very reluctant to add a new dependency, especially for something this small. I'm a little confused now around what problem or feature you're trying to solve for?

**Pull request closed without merging**
